### ISSUE TITLE
python3 manage.py crontab add not executing

### ISSUE THREAD

**Issue by Gaurav-Narayan-Varma** [kraiz/django-crontab#129]
#### Environment & Versions
* Operating system: 
* Python: 3.10.9
* Django: 4.1.1
* django-crontab: 0.7.1

#### Settings
* My `django-crontab` settings: 
```python
CRONJOBS = [
    ('50 16 * * *', 'webarticles.cron.create_nyt_entries_cron'),
    ('50 16 * * *', 'webarticles.cron.create_wsj_entries_cron')]
```

#### Details
* Output of `crontab -l` after running `python manage.py crontab add`.
```
# the CLI freezes in the following state when doing python3 manage.py crontab add:
crontab: no crontab for gauravvarma
  adding cronjob: (f99a32b150a5c47b7e0760adf46b7f85) -> ('50 16 * * *', 'webarticles.cron.create_nyt_entries_cron')
  adding cronjob: (b41157eb387884e841281ad40f0b67ab) -> ('50 16 * * *', 'webarticles.cron.create_wsj_entries_cron')
```

* If this output contained a `crontab run` command and I copy this command to my terminal the job works:
```
# when I run python3 manage.py crontab run I get the following output:
Traceback (most recent call last):
  File "/Users/gauravvarma/2023/optic/back-end/manage.py", line 22, in <module>
    main()
  File "/Users/gauravvarma/2023/optic/back-end/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/homebrew/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/homebrew/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/homebrew/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/homebrew/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/opt/homebrew/lib/python3.10/site-packages/django_crontab/management/commands/crontab.py", line 29, in handle
    Crontab().run_job(options['jobhash'])
  File "/opt/homebrew/lib/python3.10/site-packages/django_crontab/crontab.py", line 126, in run_job
    job = self.__get_job_by_hash(job_hash)
  File "/opt/homebrew/lib/python3.10/site-packages/django_crontab/crontab.py", line 171, in __get_job_by_hash
    raise RuntimeError(
RuntimeError: No job with hash None found. It seems the crontab is out of sync with your settings.CRONJOBS. Run "python manage.py crontab add" again to resolve this issue!
```

**Comment by Gaurav-Narayan-Varma** [comment]
Found the error
