### ISSUE TITLE
error create jobs for multiple sites in one server

### ISSUE THREAD

**Issue by icduicdu** [kraiz/django-crontab#33]
i have two apps in same server: /home/django/app1 /home/django/app2
if i'll run python manage.py crontab add in app1-folder it will work
but if i'll run python manage.py crontab add in app2-folder after previous step, it will print error:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django_crontab/management/commands/crontab.py", line 20, in handle
    crontab.remove_jobs()
  File "/usr/local/lib/python2.7/dist-packages/django_crontab/crontab.py", line 118, in remove_jobs
    self.__get_job_by_hash(job[0][2][job[0][2].find('crontab run') + 12:].split()[0])
  File "/usr/local/lib/python2.7/dist-packages/django_crontab/crontab.py", line 173, in __get_job_by_hash
    'Run "python manage.py crontab add" again to resolve this issue!' % job_hash
RuntimeError: No job with hash 6e36fac415c5f7df8cec638e7cfb9f5f found. It seems the crontab is out of sync with your settings.CRONJOBS. Run "python manage.py crontab add" again to resolve this issue!

```

**Comment by kraiz** [comment]
Please test with setting CRONTAB_DJANGO_PROJECT_NAME explicitly to different strings.
If this doesn't help, please provide the output of `crontab -l` before running `add` on app1 and after.

**Comment by icduicdu** [comment]
Lars, it helps!
Thank you for your response!
Thank you for that plugin, you are grate man, you develop the future :)

**Comment by kraiz** [comment]
Glad i could help :)
