### ISSUE TITLE
django crontab trigger import error

### ISSUE THREAD

**Issue by peteguan** [kraiz/django-crontab#87]
#### Environment & Versions
* Operating system: centos 6
* Python: 2.6
* Django: 1.6.10
* django-crontab: 0.6.0

#### Settings
* My `django-crontab` settings: 
```python
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app',

    'django_crontab',
)

CRONJOBS = [
 ('*/1 * * * *', 'crontab_ex.app.cron.my_job', '>> /tmp/crontab_job.log') 
]
```

#### Details
* Structure of my tiny project
```
(venv_for_django_1_6) [pete@localhost crontab_ex]$ tree
.
|-- app
|   |-- admin.py
|   |-- cron.py
|   |-- __init__.py
|   |-- __init__.pyc
|   |-- models.py
|   |-- models.pyc
|   |-- tests.py
|   `-- views.py
|-- crontab_ex
|   |-- __init__.py
|   |-- __init__.pyc
|   |-- settings.py
|   |-- settings.pyc
|   |-- urls.py
|   |-- urls.pyc
|   |-- wsgi.py
|   `-- wsgi.pyc
|-- manage.py
`-- manage.pyc
```
* Output of `crontab -l` after running `python manage.py crontab add`.
```
You have new mail in /var/mail/pete
```
and the content of this mail is like this

```
2f4a6720d4241d072 >> /tmp/crontab_job.log # django-cronjobs for crontab_ex
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=25>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/1000>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pete>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pete>
X-Cron-Env: <USER=pete>
Message-Id: <20180804055902.2D5F020DCF40@localhost.localdomain>
Date: Sat,  4 Aug 2018 13:59:02 +0800 (CST)

Traceback (most recent call last):
  File "/home/pete/PycharmProjects/crontab_ex/manage.py", line 10, in 
<module>
    execute_from_command_line(sys.argv)
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in 
execute_from_command_line
    utility.execute()
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django_crontab/management/commands/crontab.py", line 31, in handle
    Crontab().run_job(args[1])
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django_crontab/crontab.py", line 142, in run_job
    module = import_module(module_path)
  File "/home/pete/virtualenvs/venv_for_django_1_6/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named app.cron
```

Could you pls help me to find my bug?

**Comment by peteguan** [comment]
My function in `cron.py` is like this
```
import os

def my_job():
    job = os.system("date")
    return job
```

**Comment by kraiz** [comment]
try to remove `crontab_ex.` from `CRONJOBS`

**Comment by peteguan** [comment]
it works! thank you mate
